### ISSUE TITLE
Error after selecting item

### ISSUE THREAD

**Issue by mellis3** [RusinovAnton/react-select3#3]
I'm using the Fetch Select method to load a dropdown of clients. It seems to work fine to fetch the clients and display them in the dropdown.
After i select any option i get this error:
**this.updater.enqueueCallback is not a function at Select../node_modules/react-select3/dist/react-select3.umd.js.ReactComponent.setState**

I'm using React 16 - is that causing these errors?
Any other ideas what might be causing this?

It's also not firing my onChange callback function 

React is also telling me each of the items in the options_list does not have the key parameter, but it looks like the source code should be adding that to each.

**Comment by RusinovAnton** [comment]
Haven't used it with React 16 yet. Going to try migrate it.

**Comment by RusinovAnton** [comment]
> React is also telling me each of the items in the options_list does not have the key parameter, but it looks like the source code should be adding that to each.

That is strange. Snapshots are now showing key as custom attribute https://github.com/RusinovAnton/react-select3/pull/5/files#diff-14d7371846a64e26191973e5e6049709

**Comment by RusinovAnton** [comment]
@mellis3 I've just released `react-select3@4.0.0-rc.1` which is using `react@16.1.0`so it would be great if you could upgrade to and test a bit.  
Still not sure what to do with keys, going to research that a bit later.

**Comment by mellis3** [comment]
Awesome. I'll check it out over the next day or so and let you know.

**Comment by RusinovAnton** [comment]
https://github.com/facebook/react/issues/11537 here member of react have pointed me out that I'm using babel plugins wrong. Going to fix that today and release 4.0.0

**Comment by RusinovAnton** [comment]
@mellis3 
I've upgraded dependencies and fixed iterator warning. You may update react-select3 to v4 now.  
`npm install --save react-select3@4.0.0`    
Thanks for your contribution.

**Comment by mellis3** [comment]
Nice! just upgraded to v4.0.0 and all the warnings/issues are gone. Thanks for your prompt fix and your work on this. Really like it a lot, great work!
