### ISSUE TITLE
Can't get the search input to hide

### ISSUE THREAD

**Issue by mellis3** [RusinovAnton/react-select3#7]
First off, i really like the search box, great feature!

However, for a small number of items it's not needed. Using search.minimumResults or search.show parameters, like the docs suggest, doesn't seem to hide the search input.

I'm using React 16.

**Comment by RusinovAnton** [comment]
@mellis3 thanks for reporting this issue. Gonna take a look at it during this week.

**Comment by RusinovAnton** [comment]
@mellis3 the behavior is changed. Please see release notes https://github.com/RusinovAnton/react-select3/releases/tag/v4.0.1  and let me know if you still have some problems with it.
